name: Deploy the Corpauration discord bot

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  CLIENT_ID: '884501584476794880'
  GUILD_ID: '850788219133886565'
  IMAGE_NAME: corp-discord-bot-image
  CONTAINER_NAME: corp-discord-bot-container

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - name: Stop running container
        run: docker stop $CONTAINER_NAME
        # When the workflow is started for the first time the container is not running
        continue-on-error: true 
      - name: Remove previous version of the image
        run: docker rmi $IMAGE_NAME
        # When the workflow is started for the first time the image does not exist
        continue-on-error: true

  build:
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --tag $IMAGE_NAME --force-rm
  
  run:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Start the Docker container
        run: docker run -d --env TZ=Europe/Paris --env CLIENT_ID=$CLIENT_ID --env GUILD_ID=$GUILD_ID --env TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} --name $CONTAINER_NAME --rm $IMAGE_NAME
